 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import javax.swing.ImageIcon;
import vista.Airpods;
import vista.Ipad;
import vista.Iphone15;
import vista.Reloj;

/**
 *
 * @author User
 */
public class Sistema extends javax.swing.JFrame {
    public Airpods ar;
    public Ipad ip;
    public Iphone15 iph;
    public Reloj re;
    public Login lg;
    public Sistema() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("../Img/apple-logo-png-black.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIphone = new javax.swing.JLabel();
        btnIphone = new javax.swing.JButton();
        miniPadButton = new javax.swing.JButton();
        AppleWatchButton = new javax.swing.JButton();
        AirpodsButton = new javax.swing.JButton();
        lblIphone1 = new javax.swing.JLabel();
        lblIpad = new javax.swing.JLabel();
        lblAppleWatch = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblIphone.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lblIphone.setForeground(new java.awt.Color(255, 255, 255));
        lblIphone.setText("iPhone 15");

        btnIphone.setBackground(new java.awt.Color(0, 0, 0));
        btnIphone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/3ba396_143a542fcf794779aba20d55927a5d9d_mv2-removebg-preview.png"))); // NOI18N
        btnIphone.setBorder(null);
        btnIphone.setBorderPainted(false);
        btnIphone.setContentAreaFilled(false);
        btnIphone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIphoneActionPerformed(evt);
            }
        });

        miniPadButton.setBackground(new java.awt.Color(0, 0, 0));
        miniPadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/WhatsApp Image 2023-11-16 at 2.41.05 PM (1).jpeg"))); // NOI18N
        miniPadButton.setContentAreaFilled(false);
        miniPadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniPadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniPadButtonActionPerformed(evt);
            }
        });

        AppleWatchButton.setBackground(new java.awt.Color(0, 0, 0));
        AppleWatchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Apple_Watch_Series_9-removebg-preview (1) (2).png"))); // NOI18N
        AppleWatchButton.setContentAreaFilled(false);
        AppleWatchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AppleWatchButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AppleWatchButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        AppleWatchButton.setMaximumSize(new java.awt.Dimension(120, 120));
        AppleWatchButton.setMinimumSize(new java.awt.Dimension(120, 120));
        AppleWatchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppleWatchButtonActionPerformed(evt);
            }
        });

        AirpodsButton.setBackground(new java.awt.Color(0, 0, 0));
        AirpodsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/WhatsApp Image 2023-11-16 at 2.41.05 PM.jpeg"))); // NOI18N
        AirpodsButton.setContentAreaFilled(false);
        AirpodsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AirpodsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirpodsButtonActionPerformed(evt);
            }
        });

        lblIphone1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lblIphone1.setForeground(new java.awt.Color(255, 255, 255));
        lblIphone1.setText("Airpods");

        lblIpad.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lblIpad.setForeground(new java.awt.Color(255, 255, 255));
        lblIpad.setText("iPad Mini");

        lblAppleWatch.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lblAppleWatch.setForeground(new java.awt.Color(255, 255, 255));
        lblAppleWatch.setText("Apple Watch Series 9");

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel1.setText("AppleShop");

        btnLogout.setBackground(new java.awt.Color(51, 0, 51));
        btnLogout.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Log Out");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblIphone1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(AirpodsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(miniPadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIpad)
                        .addGap(121, 121, 121)))
                .addComponent(AppleWatchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAppleWatch)
                .addGap(109, 109, 109))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(lblIphone))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogout))
                            .addComponent(btnIphone, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIphone, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIphone)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(AppleWatchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(miniPadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblIpad)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AirpodsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIphone1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAppleWatch)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 850));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back.jpg"))); // NOI18N
        background.setText("jLabel1");
        background.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 560, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        lg = new Login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnIphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIphoneActionPerformed
        iph = new Iphone15();
        iph.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIphoneActionPerformed

    private void AirpodsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirpodsButtonActionPerformed
        ar = new Airpods();
        ar.setVisible(true);
        dispose();
    }//GEN-LAST:event_AirpodsButtonActionPerformed

    private void miniPadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniPadButtonActionPerformed
        ip = new Ipad();
        ip.setVisible(true);
        dispose();
    }//GEN-LAST:event_miniPadButtonActionPerformed

    private void AppleWatchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppleWatchButtonActionPerformed
        re = new Reloj();
        re.setVisible(true);
        dispose();
    }//GEN-LAST:event_AppleWatchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AirpodsButton;
    private javax.swing.JButton AppleWatchButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnIphone;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAppleWatch;
    private javax.swing.JLabel lblIpad;
    private javax.swing.JLabel lblIphone;
    private javax.swing.JLabel lblIphone1;
    private javax.swing.JButton miniPadButton;
    // End of variables declaration//GEN-END:variables
}
